version: '3'
services:
  app:
    build: .
    wordpress:
      image: wordpress
    ports:
      - "8081:80"
    environment:
       WORDPRESS_DB_PASSWORD: abc123


mysql: 
  image: mysql:latest
     environment:
       MYSQL_ROOT_PASSWORD: abc123 
